addSbtPlugin("com.github.sbt"     % "sbt-native-packager"       % "1.9.11")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.16.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"       % "0.21.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.2.0")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.5.2")
